input_file:
    "/scratch/galeov97/begendiv/pipelines_data_test/input_files.tsv"

snakemake_dir_path: 
    "/scratch/galeov97/begendiv/pipelines/assembly/snakemake"

results: 
    "/scratch/galeov97/begendiv/pipelines_data_test/results"

prefix:
    speciesX
ploidy:
    2

# genome profiling
kmersize:
    31
Lbound:
    10
Ubound:
    1500

# contigging 
genome_size_estimate: 
    80m #  '4.7m' equals '4700k' equals '4700000'
purgel: 
    "1" #Hifiasm purging parameter - 0 = no purging, 1 = purge contained haplotigs (s=0.75), 2 = purge all haplotigs (s=0.75), 3 = aggresive purging of all haplotigs (s=0.55)
contig_assembler:
    "hifiasm" # possible choices: hifiasm, hicanu, flye
