input_file:
    ../../input_files.tsv

snakemake_dir_path: 
    '/scratch/galeov97/begendiv/pipelines/assembly/snakemake'

prefix:
    test

ploidy:
    2

kmersize:
    21

Lbound:
    10

Ubound:
    1500
