import os
import glob
import sys
import pandas as pd

configfile: "config.yaml"

prefix=config["prefix"]
ploidy=config["ploidy"]
k=config["kmersize"]
L=config["Lbound"]
U=config["Ubound"]

output_meryl=config["prefix"]+".meryl"
output_smudgeplot=prefix+"_L"+str(L)+"_U"+str(U)+"_smudgeplot.png"

# Reading the input files that contain a single column called "file_path"
samples = pd.read_csv(config['input_file'], dtype=str, index_col=False, skip_blank_lines=True)
samples["sample_nr"] = [f"sample_{i+1}" for i in range(len(samples))]

# Output folders 
output_meryl=config["prefix"]+".meryl"
output_smudgeplot=prefix+"_L"+str(L)+"_U"+str(U)+"_smudgeplot.png"

include: "rules.smk"

rule all:
	input:
		output_smudgeplot,
		"Estimated_genome_size"