genome: /scratch/ddepanis/pilot/Solea_solea/asm/fSolSol10.20230412.decontaminated.fa

READ_FILES:
    A: /scratch/galeov97/begendiv/pilot/solea_solea/test_data/ERR11242127_001.fastq.gz
    B: /scratch/galeov97/begendiv/pilot/solea_solea/test_data/ERR11242127_002.fastq.gz
    C: /scratch/galeov97/begendiv/pilot/solea_solea/test_data/ERR11242127_003.fastq.gz

prefix:
    asm_mLioSpu.hap1
